DROP TABLE IF EXISTS "__EFMigrationsHistory" CASCADE;
DROP TABLE IF EXISTS "Holdings" CASCADE;
DROP TABLE IF EXISTS "Portfolios" CASCADE;
DROP TABLE IF EXISTS "Instruments" CASCADE;
DROP TABLE IF EXISTS "InstrumentTypes" CASCADE;
DROP TABLE IF EXISTS "Platforms" CASCADE;
DROP TABLE IF EXISTS "Accounts" CASCADE;