// <auto-generated />
using System;
using FtoConsulting.PortfolioManager.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FtoConsulting.PortfolioManager.Infrastructure.Migrations
{
    [DbContext(typeof(PortfolioManagerDbContext))]
    [Migration("20251003143546_AddTickerToInstrument")]
    partial class AddTickerToInstrument
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FtoConsulting.PortfolioManager.Domain.Entities.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("password");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("user_name");

                    b.HasKey("Id");

                    b.HasIndex("UserName")
                        .IsUnique()
                        .HasDatabaseName("ix_accounts_user_name");

                    b.ToTable("accounts", (string)null);
                });

            modelBuilder.Entity("FtoConsulting.PortfolioManager.Domain.Entities.Holding", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("BoughtValue")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("bought_value");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<decimal>("CurrentValue")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("current_value");

                    b.Property<decimal>("DailyProfitLoss")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("daily_profit_loss");

                    b.Property<decimal>("DailyProfitLossPercentage")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("daily_profit_loss_percentage");

                    b.Property<Guid>("InstrumentId")
                        .HasColumnType("uuid")
                        .HasColumnName("instrument_id");

                    b.Property<Guid>("PlatformId")
                        .HasColumnType("uuid")
                        .HasColumnName("platform_id");

                    b.Property<Guid>("PortfolioId")
                        .HasColumnType("uuid")
                        .HasColumnName("portfolio_id");

                    b.Property<decimal>("UnitAmount")
                        .HasPrecision(18, 8)
                        .HasColumnType("numeric(18,8)")
                        .HasColumnName("unit_amount");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<DateTime>("ValuationDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("valuation_date");

                    b.HasKey("Id");

                    b.HasIndex("InstrumentId");

                    b.HasIndex("PlatformId");

                    b.HasIndex("PortfolioId")
                        .HasDatabaseName("ix_holdings_portfolio_id");

                    b.HasIndex("ValuationDate")
                        .HasDatabaseName("ix_holdings_valuation_date");

                    b.HasIndex("PortfolioId", "InstrumentId", "ValuationDate")
                        .HasDatabaseName("ix_holdings_portfolio_instrument_date");

                    b.ToTable("holdings", (string)null);
                });

            modelBuilder.Entity("FtoConsulting.PortfolioManager.Domain.Entities.Instrument", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<string>("ISIN")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)")
                        .HasColumnName("isin");

                    b.Property<Guid>("InstrumentTypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("instrument_type_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("SEDOL")
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)")
                        .HasColumnName("sedol");

                    b.Property<string>("Ticker")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("ticker");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("ISIN")
                        .IsUnique()
                        .HasDatabaseName("ix_instruments_isin");

                    b.HasIndex("InstrumentTypeId");

                    b.HasIndex("Name")
                        .HasDatabaseName("ix_instruments_name");

                    b.HasIndex("SEDOL")
                        .HasDatabaseName("ix_instruments_sedol");

                    b.HasIndex("Ticker")
                        .HasDatabaseName("ix_instruments_ticker");

                    b.ToTable("instruments", (string)null);
                });

            modelBuilder.Entity("FtoConsulting.PortfolioManager.Domain.Entities.InstrumentType", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_instrument_types_name");

                    b.ToTable("instrument_types", (string)null);
                });

            modelBuilder.Entity("FtoConsulting.PortfolioManager.Domain.Entities.Platform", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_platforms_name");

                    b.ToTable("platforms", (string)null);
                });

            modelBuilder.Entity("FtoConsulting.PortfolioManager.Domain.Entities.Portfolio", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("AccountId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_portfolios_account_id_name");

                    b.ToTable("portfolios", (string)null);
                });

            modelBuilder.Entity("FtoConsulting.PortfolioManager.Domain.Entities.Holding", b =>
                {
                    b.HasOne("FtoConsulting.PortfolioManager.Domain.Entities.Instrument", "Instrument")
                        .WithMany("Holdings")
                        .HasForeignKey("InstrumentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FtoConsulting.PortfolioManager.Domain.Entities.Platform", "Platform")
                        .WithMany("Holdings")
                        .HasForeignKey("PlatformId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FtoConsulting.PortfolioManager.Domain.Entities.Portfolio", "Portfolio")
                        .WithMany("Holdings")
                        .HasForeignKey("PortfolioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Instrument");

                    b.Navigation("Platform");

                    b.Navigation("Portfolio");
                });

            modelBuilder.Entity("FtoConsulting.PortfolioManager.Domain.Entities.Instrument", b =>
                {
                    b.HasOne("FtoConsulting.PortfolioManager.Domain.Entities.InstrumentType", "InstrumentType")
                        .WithMany("Instruments")
                        .HasForeignKey("InstrumentTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("InstrumentType");
                });

            modelBuilder.Entity("FtoConsulting.PortfolioManager.Domain.Entities.Portfolio", b =>
                {
                    b.HasOne("FtoConsulting.PortfolioManager.Domain.Entities.Account", "Account")
                        .WithMany("Portfolios")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("FtoConsulting.PortfolioManager.Domain.Entities.Account", b =>
                {
                    b.Navigation("Portfolios");
                });

            modelBuilder.Entity("FtoConsulting.PortfolioManager.Domain.Entities.Instrument", b =>
                {
                    b.Navigation("Holdings");
                });

            modelBuilder.Entity("FtoConsulting.PortfolioManager.Domain.Entities.InstrumentType", b =>
                {
                    b.Navigation("Instruments");
                });

            modelBuilder.Entity("FtoConsulting.PortfolioManager.Domain.Entities.Platform", b =>
                {
                    b.Navigation("Holdings");
                });

            modelBuilder.Entity("FtoConsulting.PortfolioManager.Domain.Entities.Portfolio", b =>
                {
                    b.Navigation("Holdings");
                });
#pragma warning restore 612, 618
        }
    }
}
