// <auto-generated />
using System;
using FtoConsulting.PortfolioManager.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FtoConsulting.PortfolioManager.Infrastructure.Migrations
{
    [DbContext(typeof(PortfolioManagerDbContext))]
    [Migration("20250926110930_InitialCreateSnakeCase")]
    partial class InitialCreateSnakeCase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FtoConsulting.PortfolioManager.Domain.Entities.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("password");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("user_name");

                    b.HasKey("Id")
                        .HasName("pk_accounts");

                    b.HasIndex("UserName")
                        .IsUnique()
                        .HasDatabaseName("IX_Accounts_UserName");

                    b.ToTable("Accounts", (string)null);
                });

            modelBuilder.Entity("FtoConsulting.PortfolioManager.Domain.Entities.Holding", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("BoughtValue")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("bought_value");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<decimal>("CurrentValue")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("current_value");

                    b.Property<decimal>("DailyProfitLoss")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("daily_profit_loss");

                    b.Property<decimal>("DailyProfitLossPercentage")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("daily_profit_loss_percentage");

                    b.Property<Guid>("InstrumentId")
                        .HasColumnType("uuid")
                        .HasColumnName("instrument_id");

                    b.Property<Guid>("PlatformId")
                        .HasColumnType("uuid")
                        .HasColumnName("platform_id");

                    b.Property<Guid>("PortfolioId")
                        .HasColumnType("uuid")
                        .HasColumnName("portfolio_id");

                    b.Property<decimal>("UnitAmount")
                        .HasPrecision(18, 8)
                        .HasColumnType("numeric(18,8)")
                        .HasColumnName("unit_amount");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<DateTime>("ValuationDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("valuation_date");

                    b.HasKey("Id")
                        .HasName("pk_holdings");

                    b.HasIndex("InstrumentId")
                        .HasDatabaseName("ix_holdings_instrument_id");

                    b.HasIndex("PlatformId")
                        .HasDatabaseName("ix_holdings_platform_id");

                    b.HasIndex("PortfolioId")
                        .HasDatabaseName("IX_Holdings_PortfolioId");

                    b.HasIndex("ValuationDate")
                        .HasDatabaseName("IX_Holdings_ValuationDate");

                    b.HasIndex("PortfolioId", "InstrumentId", "ValuationDate")
                        .HasDatabaseName("IX_Holdings_Portfolio_Instrument_Date");

                    b.ToTable("Holdings", (string)null);
                });

            modelBuilder.Entity("FtoConsulting.PortfolioManager.Domain.Entities.Instrument", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<string>("ISIN")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)")
                        .HasColumnName("isin");

                    b.Property<Guid>("InstrumentTypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("instrument_type_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("SEDOL")
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)")
                        .HasColumnName("sedol");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_instruments");

                    b.HasIndex("ISIN")
                        .IsUnique()
                        .HasDatabaseName("IX_Instruments_ISIN");

                    b.HasIndex("InstrumentTypeId")
                        .HasDatabaseName("ix_instruments_instrument_type_id");

                    b.HasIndex("Name")
                        .HasDatabaseName("IX_Instruments_Name");

                    b.HasIndex("SEDOL")
                        .HasDatabaseName("IX_Instruments_SEDOL");

                    b.ToTable("Instruments", (string)null);
                });

            modelBuilder.Entity("FtoConsulting.PortfolioManager.Domain.Entities.InstrumentType", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_instrument_types");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("IX_InstrumentTypes_Name");

                    b.ToTable("InstrumentTypes", (string)null);
                });

            modelBuilder.Entity("FtoConsulting.PortfolioManager.Domain.Entities.Platform", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_platforms");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("IX_Platforms_Name");

                    b.ToTable("Platforms", (string)null);
                });

            modelBuilder.Entity("FtoConsulting.PortfolioManager.Domain.Entities.Portfolio", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_portfolios");

                    b.HasIndex("AccountId", "Name")
                        .IsUnique()
                        .HasDatabaseName("IX_Portfolios_AccountId_Name");

                    b.ToTable("Portfolios", (string)null);
                });

            modelBuilder.Entity("FtoConsulting.PortfolioManager.Domain.Entities.Holding", b =>
                {
                    b.HasOne("FtoConsulting.PortfolioManager.Domain.Entities.Instrument", "Instrument")
                        .WithMany("Holdings")
                        .HasForeignKey("InstrumentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_holdings_instruments_instrument_id");

                    b.HasOne("FtoConsulting.PortfolioManager.Domain.Entities.Platform", "Platform")
                        .WithMany("Holdings")
                        .HasForeignKey("PlatformId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_holdings_platforms_platform_id");

                    b.HasOne("FtoConsulting.PortfolioManager.Domain.Entities.Portfolio", "Portfolio")
                        .WithMany("Holdings")
                        .HasForeignKey("PortfolioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_holdings_portfolios_portfolio_id");

                    b.Navigation("Instrument");

                    b.Navigation("Platform");

                    b.Navigation("Portfolio");
                });

            modelBuilder.Entity("FtoConsulting.PortfolioManager.Domain.Entities.Instrument", b =>
                {
                    b.HasOne("FtoConsulting.PortfolioManager.Domain.Entities.InstrumentType", "InstrumentType")
                        .WithMany("Instruments")
                        .HasForeignKey("InstrumentTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_instruments_instrument_types_instrument_type_id");

                    b.Navigation("InstrumentType");
                });

            modelBuilder.Entity("FtoConsulting.PortfolioManager.Domain.Entities.Portfolio", b =>
                {
                    b.HasOne("FtoConsulting.PortfolioManager.Domain.Entities.Account", "Account")
                        .WithMany("Portfolios")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_portfolios_accounts_account_id");

                    b.Navigation("Account");
                });

            modelBuilder.Entity("FtoConsulting.PortfolioManager.Domain.Entities.Account", b =>
                {
                    b.Navigation("Portfolios");
                });

            modelBuilder.Entity("FtoConsulting.PortfolioManager.Domain.Entities.Instrument", b =>
                {
                    b.Navigation("Holdings");
                });

            modelBuilder.Entity("FtoConsulting.PortfolioManager.Domain.Entities.InstrumentType", b =>
                {
                    b.Navigation("Instruments");
                });

            modelBuilder.Entity("FtoConsulting.PortfolioManager.Domain.Entities.Platform", b =>
                {
                    b.Navigation("Holdings");
                });

            modelBuilder.Entity("FtoConsulting.PortfolioManager.Domain.Entities.Portfolio", b =>
                {
                    b.Navigation("Holdings");
                });
#pragma warning restore 612, 618
        }
    }
}
