// <auto-generated />
using System;
using FtoConsulting.PortfolioManager.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FtoConsulting.PortfolioManager.Infrastructure.Migrations
{
    [DbContext(typeof(PortfolioManagerDbContext))]
    [Migration("20251106160948_AddMemoryEntities")]
    partial class AddMemoryEntities
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FtoConsulting.PortfolioManager.Domain.Entities.Account", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("password");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("user_name");

                    b.HasKey("Id");

                    b.HasIndex("UserName")
                        .IsUnique()
                        .HasDatabaseName("ix_accounts_user_name");

                    b.ToTable("accounts", "app");
                });

            modelBuilder.Entity("FtoConsulting.PortfolioManager.Domain.Entities.ChatMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<int>("ConversationThreadId")
                        .HasColumnType("integer")
                        .HasColumnName("conversation_thread_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("MessageTimestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("message_timestamp");

                    b.Property<string>("Metadata")
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("role");

                    b.Property<int>("TokenCount")
                        .HasColumnType("integer")
                        .HasColumnName("token_count");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("ConversationThreadId")
                        .HasDatabaseName("ix_chat_messages_conversation_thread_id");

                    b.HasIndex("MessageTimestamp")
                        .HasDatabaseName("ix_chat_messages_message_timestamp");

                    b.HasIndex("ConversationThreadId", "MessageTimestamp")
                        .HasDatabaseName("ix_chat_messages_thread_id_timestamp");

                    b.ToTable("chat_messages", "app");
                });

            modelBuilder.Entity("FtoConsulting.PortfolioManager.Domain.Entities.ConversationThread", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AccountId")
                        .HasColumnType("integer")
                        .HasColumnName("account_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<DateTime>("LastActivity")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_activity");

                    b.Property<string>("ThreadTitle")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("thread_title");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("AccountId")
                        .HasDatabaseName("ix_conversation_threads_account_id");

                    b.HasIndex("LastActivity")
                        .HasDatabaseName("ix_conversation_threads_last_activity");

                    b.HasIndex("AccountId", "IsActive")
                        .HasDatabaseName("ix_conversation_threads_account_id_is_active");

                    b.ToTable("conversation_threads", "app");
                });

            modelBuilder.Entity("FtoConsulting.PortfolioManager.Domain.Entities.ExchangeRate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BaseCurrency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("base_currency");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("FetchedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fetched_at");

                    b.Property<decimal>("Rate")
                        .HasColumnType("decimal(18,8)")
                        .HasColumnName("rate");

                    b.Property<DateOnly>("RateDate")
                        .HasColumnType("date")
                        .HasColumnName("rate_date");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("source");

                    b.Property<string>("TargetCurrency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("target_currency");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("RateDate")
                        .HasDatabaseName("ix_exchange_rates_rate_date");

                    b.HasIndex("BaseCurrency", "TargetCurrency")
                        .HasDatabaseName("ix_exchange_rates_currency_pair");

                    b.HasIndex("BaseCurrency", "TargetCurrency", "RateDate")
                        .IsUnique()
                        .HasDatabaseName("ix_exchange_rates_currency_pair_date");

                    b.ToTable("exchange_rates", "app");
                });

            modelBuilder.Entity("FtoConsulting.PortfolioManager.Domain.Entities.Holding", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("BoughtValue")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("bought_value");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<decimal>("CurrentValue")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("current_value");

                    b.Property<decimal>("DailyProfitLoss")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("daily_profit_loss");

                    b.Property<decimal>("DailyProfitLossPercentage")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("daily_profit_loss_percentage");

                    b.Property<int>("InstrumentId")
                        .HasColumnType("integer")
                        .HasColumnName("instrument_id");

                    b.Property<int>("PlatformId")
                        .HasColumnType("integer")
                        .HasColumnName("platform_id");

                    b.Property<int>("PortfolioId")
                        .HasColumnType("integer")
                        .HasColumnName("portfolio_id");

                    b.Property<decimal>("UnitAmount")
                        .HasPrecision(18, 8)
                        .HasColumnType("numeric(18,8)")
                        .HasColumnName("unit_amount");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<DateTime>("ValuationDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("valuation_date");

                    b.HasKey("Id");

                    b.HasIndex("InstrumentId");

                    b.HasIndex("PlatformId");

                    b.HasIndex("PortfolioId")
                        .HasDatabaseName("ix_holdings_portfolio_id");

                    b.HasIndex("ValuationDate")
                        .HasDatabaseName("ix_holdings_valuation_date");

                    b.HasIndex("PortfolioId", "InstrumentId", "ValuationDate")
                        .HasDatabaseName("ix_holdings_portfolio_instrument_date");

                    b.ToTable("holdings", "app");
                });

            modelBuilder.Entity("FtoConsulting.PortfolioManager.Domain.Entities.Instrument", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CurrencyCode")
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency_code");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<int>("InstrumentTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("instrument_type_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("QuoteUnit")
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("quote_unit");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("ticker");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("CurrencyCode")
                        .HasDatabaseName("ix_instruments_currency_code");

                    b.HasIndex("InstrumentTypeId");

                    b.HasIndex("Name")
                        .HasDatabaseName("ix_instruments_name");

                    b.HasIndex("QuoteUnit")
                        .HasDatabaseName("ix_instruments_quote_unit");

                    b.HasIndex("Ticker")
                        .IsUnique()
                        .HasDatabaseName("ix_instruments_ticker");

                    b.ToTable("instruments", "app");
                });

            modelBuilder.Entity("FtoConsulting.PortfolioManager.Domain.Entities.InstrumentPrice", b =>
                {
                    b.Property<int>("InstrumentId")
                        .HasColumnType("integer")
                        .HasColumnName("instrument_id");

                    b.Property<DateOnly>("ValuationDate")
                        .HasColumnType("date")
                        .HasColumnName("valuation_date");

                    b.Property<decimal?>("Change")
                        .HasColumnType("decimal(18,4)")
                        .HasColumnName("change");

                    b.Property<decimal?>("ChangePercent")
                        .HasColumnType("decimal(8,4)")
                        .HasColumnName("change_percent");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency");

                    b.Property<decimal?>("High")
                        .HasColumnType("decimal(18,4)")
                        .HasColumnName("high");

                    b.Property<decimal?>("Low")
                        .HasColumnType("decimal(18,4)")
                        .HasColumnName("low");

                    b.Property<string>("Market")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("market");

                    b.Property<string>("MarketStatus")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("market_status");

                    b.Property<string>("Name")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<decimal?>("Open")
                        .HasColumnType("decimal(18,4)")
                        .HasColumnName("open");

                    b.Property<decimal?>("PreviousClose")
                        .HasColumnType("decimal(18,4)")
                        .HasColumnName("previous_close");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,4)")
                        .HasColumnName("price");

                    b.Property<DateTime?>("PriceTimestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("price_timestamp");

                    b.Property<string>("Ticker")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("ticker");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<long?>("Volume")
                        .HasColumnType("bigint")
                        .HasColumnName("volume");

                    b.HasKey("InstrumentId", "ValuationDate");

                    b.HasIndex("InstrumentId")
                        .HasDatabaseName("ix_instrument_prices_instrument_id");

                    b.HasIndex("Ticker")
                        .HasDatabaseName("ix_instrument_prices_ticker");

                    b.HasIndex("ValuationDate")
                        .HasDatabaseName("ix_instrument_prices_valuation_date");

                    b.ToTable("instrument_prices", "app");
                });

            modelBuilder.Entity("FtoConsulting.PortfolioManager.Domain.Entities.InstrumentType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_instrument_types_name");

                    b.ToTable("instrument_types", "app");
                });

            modelBuilder.Entity("FtoConsulting.PortfolioManager.Domain.Entities.MemorySummary", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ConversationThreadId")
                        .HasColumnType("integer")
                        .HasColumnName("conversation_thread_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("KeyTopics")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("key_topics");

                    b.Property<int>("MessageCount")
                        .HasColumnType("integer")
                        .HasColumnName("message_count");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("summary");

                    b.Property<DateOnly>("SummaryDate")
                        .HasColumnType("date")
                        .HasColumnName("summary_date");

                    b.Property<int>("TotalTokens")
                        .HasColumnType("integer")
                        .HasColumnName("total_tokens");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UserPreferences")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("user_preferences");

                    b.HasKey("Id");

                    b.HasIndex("ConversationThreadId")
                        .HasDatabaseName("ix_memory_summaries_conversation_thread_id");

                    b.HasIndex("SummaryDate")
                        .HasDatabaseName("ix_memory_summaries_summary_date");

                    b.HasIndex("ConversationThreadId", "SummaryDate")
                        .IsUnique()
                        .HasDatabaseName("ix_memory_summaries_thread_id_date");

                    b.ToTable("memory_summaries", "app");
                });

            modelBuilder.Entity("FtoConsulting.PortfolioManager.Domain.Entities.Platform", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_platforms_name");

                    b.ToTable("platforms", "app");
                });

            modelBuilder.Entity("FtoConsulting.PortfolioManager.Domain.Entities.Portfolio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AccountId")
                        .HasColumnType("integer")
                        .HasColumnName("account_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("AccountId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_portfolios_account_id_name");

                    b.ToTable("portfolios", "app");
                });

            modelBuilder.Entity("FtoConsulting.PortfolioManager.Domain.Entities.ChatMessage", b =>
                {
                    b.HasOne("FtoConsulting.PortfolioManager.Domain.Entities.ConversationThread", "ConversationThread")
                        .WithMany("Messages")
                        .HasForeignKey("ConversationThreadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ConversationThread");
                });

            modelBuilder.Entity("FtoConsulting.PortfolioManager.Domain.Entities.ConversationThread", b =>
                {
                    b.HasOne("FtoConsulting.PortfolioManager.Domain.Entities.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("FtoConsulting.PortfolioManager.Domain.Entities.Holding", b =>
                {
                    b.HasOne("FtoConsulting.PortfolioManager.Domain.Entities.Instrument", "Instrument")
                        .WithMany("Holdings")
                        .HasForeignKey("InstrumentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FtoConsulting.PortfolioManager.Domain.Entities.Platform", "Platform")
                        .WithMany("Holdings")
                        .HasForeignKey("PlatformId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FtoConsulting.PortfolioManager.Domain.Entities.Portfolio", "Portfolio")
                        .WithMany("Holdings")
                        .HasForeignKey("PortfolioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Instrument");

                    b.Navigation("Platform");

                    b.Navigation("Portfolio");
                });

            modelBuilder.Entity("FtoConsulting.PortfolioManager.Domain.Entities.Instrument", b =>
                {
                    b.HasOne("FtoConsulting.PortfolioManager.Domain.Entities.InstrumentType", "InstrumentType")
                        .WithMany("Instruments")
                        .HasForeignKey("InstrumentTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("InstrumentType");
                });

            modelBuilder.Entity("FtoConsulting.PortfolioManager.Domain.Entities.InstrumentPrice", b =>
                {
                    b.HasOne("FtoConsulting.PortfolioManager.Domain.Entities.Instrument", "Instrument")
                        .WithMany()
                        .HasForeignKey("InstrumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Instrument");
                });

            modelBuilder.Entity("FtoConsulting.PortfolioManager.Domain.Entities.MemorySummary", b =>
                {
                    b.HasOne("FtoConsulting.PortfolioManager.Domain.Entities.ConversationThread", "ConversationThread")
                        .WithMany("Summaries")
                        .HasForeignKey("ConversationThreadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ConversationThread");
                });

            modelBuilder.Entity("FtoConsulting.PortfolioManager.Domain.Entities.Portfolio", b =>
                {
                    b.HasOne("FtoConsulting.PortfolioManager.Domain.Entities.Account", "Account")
                        .WithMany("Portfolios")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("FtoConsulting.PortfolioManager.Domain.Entities.Account", b =>
                {
                    b.Navigation("Portfolios");
                });

            modelBuilder.Entity("FtoConsulting.PortfolioManager.Domain.Entities.ConversationThread", b =>
                {
                    b.Navigation("Messages");

                    b.Navigation("Summaries");
                });

            modelBuilder.Entity("FtoConsulting.PortfolioManager.Domain.Entities.Instrument", b =>
                {
                    b.Navigation("Holdings");
                });

            modelBuilder.Entity("FtoConsulting.PortfolioManager.Domain.Entities.InstrumentType", b =>
                {
                    b.Navigation("Instruments");
                });

            modelBuilder.Entity("FtoConsulting.PortfolioManager.Domain.Entities.Platform", b =>
                {
                    b.Navigation("Holdings");
                });

            modelBuilder.Entity("FtoConsulting.PortfolioManager.Domain.Entities.Portfolio", b =>
                {
                    b.Navigation("Holdings");
                });
#pragma warning restore 612, 618
        }
    }
}
